### ISSUE TITLE
Palette colors 16,32,…240?

### ISSUE THREAD

**Issue by vmedea** [dan-rodrigues/icestation-32#18]
Officially the palette has 256 colors, but it seems impossible to use some of these colors. The 4 LSB for pixels are taken from the tile graphics, where (local) color 0x0 always means transparent. When the hindmost layer is transparent it will default to (global) color 0x00. Does this mean that other `0x?0` palette color indices (so 16,32,…240) are never used?

**Comment by dan-rodrigues** [comment]
These colors usually aren't used. They can be used with the affine layer since it's an 8bit layer. It gets a special opacity check [here](https://github.com/dan-rodrigues/icestation-32/blob/master/hardware/vdp/vdp_priority_compute.v#L37) since only color 0 will make it transparent with the rest being opaque.

**Comment by vmedea** [comment]
Thanks for the explanation, glad to know my reasoning here was on the right track. I wasn't aware that the affine layer was fully 8-bit! Haven't really done anything with that yet.

So this seems to be by design, and was more of a question in the first place, so closing the issue.
